name: Build and Deploy Test
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          yarn
          yarn build:static
      - name: Deploy to test 🚀
        uses: tagus/git-deploy@v0.4.1
        with:
          changes: out
          repository: git@github.com:SavvyAS/testsavvyas.github.io.git
          ssh_key: ${{ secrets.CI_KEY }}
          name: kwrl
          email: hakon@savvy.no
